-- =ファイルへんか= =ファイル変化= /supabase-setup.sql

-- =========================================================
-- 食レポ同好会 Supabase 初期セットアップSQL
-- Supabase SQL Editorで一括実行してください。
-- =========================================================

create extension if not exists pgcrypto;

-- -------------------------
-- Tables
-- -------------------------

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  display_name text not null,
  icon_url text,
  bio text default '',
  is_admin boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.genres (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  genre text not null,
  image_url text not null,
  comment text not null check (char_length(comment) <= 2000),
  created_at timestamptz not null default now()
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) <= 1000),
  created_at timestamptz not null default now()
);

create table if not exists public.votes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  post_id bigint not null references public.posts(id) on delete cascade,
  week_start date not null,
  created_at timestamptz not null default now(),
  constraint votes_one_per_user_per_week unique (user_id, week_start)
);

create table if not exists public.badges (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  badge_type text not null check (
    badge_type in (
      'first_post',
      'post_10',
      'kaikin_7',
      'kaikin_14',
      'comment_king',
      'reporter'
    )
  ),
  first_earned_at timestamptz not null default now(),
  constraint badges_unique_per_user unique (user_id, badge_type)
);

create table if not exists public.weekly_titles (
  id bigint generated by default as identity primary key,
  title_type text not null check (title_type in ('comment_king', 'reporter')),
  week_start date not null,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint weekly_titles_unique unique (title_type, week_start)
);

-- -------------------------
-- Indexes
-- -------------------------

create index if not exists posts_user_id_idx on public.posts(user_id);
create index if not exists posts_genre_idx on public.posts(genre);
create index if not exists posts_created_at_idx on public.posts(created_at desc);

create index if not exists comments_post_id_idx on public.comments(post_id);
create index if not exists comments_user_id_idx on public.comments(user_id);
create index if not exists comments_created_at_idx on public.comments(created_at desc);

create index if not exists votes_post_id_idx on public.votes(post_id);
create index if not exists votes_week_start_idx on public.votes(week_start);

create index if not exists badges_user_id_idx on public.badges(user_id);
create index if not exists weekly_titles_week_start_idx on public.weekly_titles(week_start desc);

-- -------------------------
-- Default genres
-- -------------------------

insert into public.genres (name) values
  ('焼肉'),
  ('ラーメン'),
  ('スイーツ'),
  ('定食'),
  ('カレー'),
  ('寿司'),
  ('パン'),
  ('弁当'),
  ('コンビニ飯'),
  ('自炊'),
  ('カフェ'),
  ('その他')
on conflict (name) do nothing;

-- -------------------------
-- Storage bucket
-- ダッシュボードから作ってもOK。
-- -------------------------

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'post-images',
  'post-images',
  true,
  52428800,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- -------------------------
-- Grants
-- RLSが実際の制御を行います。
-- -------------------------

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on all tables in schema public to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- -------------------------
-- Enable RLS
-- -------------------------

alter table public.profiles enable row level security;
alter table public.genres enable row level security;
alter table public.posts enable row level security;
alter table public.comments enable row level security;
alter table public.votes enable row level security;
alter table public.badges enable row level security;
alter table public.weekly_titles enable row level security;

-- -------------------------
-- Helper condition for admin
-- -------------------------
-- is_admin=true のprofiles行を持つユーザーを運営扱いにします。
-- 例:
-- update public.profiles set is_admin = true where username = 'admin_username';

-- -------------------------
-- Drop old policies
-- -------------------------

drop policy if exists "profiles are viewable by authenticated users" on public.profiles;
drop policy if exists "users can insert own profile" on public.profiles;

drop policy if exists "genres are viewable by authenticated users" on public.genres;
drop policy if exists "admins can insert genres" on public.genres;
drop policy if exists "admins can update genres" on public.genres;
drop policy if exists "admins can delete genres" on public.genres;

drop policy if exists "posts are viewable by authenticated users" on public.posts;
drop policy if exists "users can insert own posts" on public.posts;

drop policy if exists "comments are viewable by authenticated users" on public.comments;
drop policy if exists "users can insert own comments" on public.comments;
drop policy if exists "admins can delete comments" on public.comments;

drop policy if exists "votes are viewable by authenticated users" on public.votes;
drop policy if exists "users can insert own votes" on public.votes;

drop policy if exists "badges are viewable by authenticated users" on public.badges;
drop policy if exists "users can insert own or weekly title badges" on public.badges;

drop policy if exists "weekly titles are viewable by authenticated users" on public.weekly_titles;
drop policy if exists "authenticated users can insert weekly titles" on public.weekly_titles;
drop policy if exists "authenticated users can update weekly titles" on public.weekly_titles;
drop policy if exists "admins can delete weekly titles" on public.weekly_titles;

-- -------------------------
-- profiles policies
-- -------------------------

create policy "profiles are viewable by authenticated users"
on public.profiles
for select
to authenticated
using (true);

create policy "users can insert own profile"
on public.profiles
for insert
to authenticated
with check (auth.uid() = id and is_admin = false);

-- -------------------------
-- genres policies
-- -------------------------

create policy "genres are viewable by authenticated users"
on public.genres
for select
to authenticated
using (true);

create policy "admins can insert genres"
on public.genres
for insert
to authenticated
with check (
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid()
    and profiles.is_admin = true
  )
);

create policy "admins can update genres"
on public.genres
for update
to authenticated
using (
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid()
    and profiles.is_admin = true
  )
)
with check (
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid()
    and profiles.is_admin = true
  )
);

create policy "admins can delete genres"
on public.genres
for delete
to authenticated
using (
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid()
    and profiles.is_admin = true
  )
);

-- -------------------------
-- posts policies
-- -------------------------

create policy "posts are viewable by authenticated users"
on public.posts
for select
to authenticated
using (true);

create policy "users can insert own posts"
on public.posts
for insert
to authenticated
with check (auth.uid() = user_id);

-- -------------------------
-- comments policies
-- -------------------------

create policy "comments are viewable by authenticated users"
on public.comments
for select
to authenticated
using (true);

create policy "users can insert own comments"
on public.comments
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "admins can delete comments"
on public.comments
for delete
to authenticated
using (
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid()
    and profiles.is_admin = true
  )
);

-- -------------------------
-- votes policies
-- -------------------------

create policy "votes are viewable by authenticated users"
on public.votes
for select
to authenticated
using (true);

create policy "users can insert own votes"
on public.votes
for insert
to authenticated
with check (auth.uid() = user_id);

-- -------------------------
-- badges policies
-- 永久バッジは自分のみ。
-- comment_king / reporter はクライアント週次集計のためログインユーザーが記録可能。
-- -------------------------

create policy "badges are viewable by authenticated users"
on public.badges
for select
to authenticated
using (true);

create policy "users can insert own or weekly title badges"
on public.badges
for insert
to authenticated
with check (
  auth.uid() = user_id
  or badge_type in ('comment_king', 'reporter')
);

-- -------------------------
-- weekly_titles policies
-- 静的サイトで週次集計を更新するため、ログインユーザーにinsert/update許可。
-- -------------------------

create policy "weekly titles are viewable by authenticated users"
on public.weekly_titles
for select
to authenticated
using (true);

create policy "authenticated users can insert weekly titles"
on public.weekly_titles
for insert
to authenticated
with check (true);

create policy "authenticated users can update weekly titles"
on public.weekly_titles
for update
to authenticated
using (true)
with check (true);

create policy "admins can delete weekly titles"
on public.weekly_titles
for delete
to authenticated
using (
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid()
    and profiles.is_admin = true
  )
);

-- -------------------------
-- Storage policies
-- -------------------------

drop policy if exists "post images are publicly readable" on storage.objects;
drop policy if exists "authenticated users can upload own post images" on storage.objects;
drop policy if exists "users can update own post images" on storage.objects;
drop policy if exists "users can delete own post images" on storage.objects;

create policy "post images are publicly readable"
on storage.objects
for select
to public
using (bucket_id = 'post-images');

create policy "authenticated users can upload own post images"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'post-images'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "users can update own post images"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'post-images'
  and (storage.foldername(name))[1] = auth.uid()::text
)
with check (
  bucket_id = 'post-images'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "users can delete own post images"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'post-images'
  and (storage.foldername(name))[1] = auth.uid()::text
);
